export const GET_COUNTRIES = 'GET_COUNTRIES';

export const ORDER_COUNTRIES_ALF = 'ORDER_COUNTRIES_ALF';

export const ORDER_COUNTRIES_POP = 'ORDER_COUNTRIES_POP';

export const GET_COUNTRY_DETAIL = 'GET_COUNTRY_DETAIL';

export const FILTER_BY_CONTINENT = 'FILTER_BY_CONTINENT';

export const GET_COUNTRIES_BY_NAME = 'GET_COUNTRIES_BY_NAME';

export const SET_PAGE = 'SET_PAGE';

export const LOADING_ACTION = 'LOADING_ACTION';

export const POST_ACTIVITIES = 'POST_ACTIVITIES';

export const GET_ACTIVITIES = 'GET_ACTIVITIES';

export const CLEAN_STATE = 'CLEAN_STATE'
